language: java
sudo: true
dist: trusty
jdk:
  - openjdk8
services:
  - postgresql
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
before_script:
  - psql -c "CREATE USER toor WITH PASSWORD 'toor';" -U postgres
  - psql -c "CREATE DATABASE tanzania_regions;" -U toor